"use client";

import { use, useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import styles from "./track.module.css";
import Sidebar from "../../../components/Sidebar";
import Footer from "../../../components/Footer";
import useAuth from "../../hooks/useAuth";
import { legacyAPI, trackAPI } from "../../../utils/api";

export default function TrackPage({ params }) {
  const router = useRouter();
  const resolvedParams = use(params);
  const trackSlug = resolvedParams.trackId;
  const name = Array.isArray(trackSlug) ? trackSlug[0] : trackSlug || "";

  const { isAuthenticated, loading: authLoading } = useAuth();
  const [currentNode, setCurrentNode] = useState(0);
  const [lessons, setLessons] = useState([]);
  const [tasks, setTasks] = useState([]);
  const [lessonTaskMap, setLessonTaskMap] = useState({});
  const [activeLesson, setActiveLesson] = useState(null);
  const [showCompleted, setShowCompleted] = useState(true);
  const [trackProgress, setTrackProgress] = useState(null);
  const [completedTaskIds, setCompletedTaskIds] = useState(new Set());
  const [isLoading, setIsLoading] = useState(true);

  // Auth check
  useEffect(() => {
    if (!authLoading && !isAuthenticated) {
      router.push("/login");
    }
  }, [isAuthenticated, authLoading, router]);

  // Fetch track data and progress
  useEffect(() => {
    async function fetchData() {
      if (!name || !isAuthenticated) return;

      try {
        setIsLoading(true);

        // Fetch lessons
        const lessonsResponse = await legacyAPI.getLessons(name);
        const fetchedLessons = lessonsResponse.data.lessons || [];
        setLessons(fetchedLessons);

        // Generate 3 placeholder tasks for each lesson
        // These will be dynamically generated by AI when the user clicks on them
        const generatedTasks = [];
        fetchedLessons.forEach((lesson, lessonIndex) => {
          for (let i = 1; i <= 3; i++) {
            generatedTasks.push({
              id: `${lessonIndex + 1}-${i}`,
              label: `Task ${i}`,
              description: `Complete task ${i} for ${lesson.title}`,
              difficulty: i === 1 ? "Easy" : i === 2 ? "Medium" : "Hard",
              lessonIndex: lessonIndex,
              taskNumber: i
            });
          }
        });
        setTasks(generatedTasks);

        // Fetch user progress for this track
        const progressRes = await trackAPI.getProgress(name);
        setTrackProgress(progressRes.data);

        // If not enrolled, we might want to suggest enrolling
        if (!progressRes.data.is_enrolled) {
          // For now just continue, but in real app we'd redirect or show join button
        }

        // Fetch completed tasks
        const completedRes = await trackAPI.getCompletedTasks(name);
        const completedIds = new Set(completedRes.data.map(t => t.task_id));
        setCompletedTaskIds(completedIds);

        // Find current node (first incomplete task)
        const firstIncompleteIdx = generatedTasks.findIndex(task => !completedIds.has(task.id));
        if (firstIncompleteIdx !== -1) {
          setCurrentNode(firstIncompleteIdx);
        } else {
          setCurrentNode(generatedTasks.length > 0 ? generatedTasks.length - 1 : 0);
        }

      } catch (err) {
        console.error("Data fetch error", err);
      } finally {
        setIsLoading(false);
      }
    }

    fetchData();
  }, [name, isAuthenticated]);

  // Group tasks by lesson
  useEffect(() => {
    if (lessons.length && tasks.length) {
      const mapping = {};

      lessons.forEach((lesson, lessonIndex) => {
        // Get tasks for this lesson
        const lessonTasks = tasks.filter(t => t.lessonIndex === lessonIndex);

        mapping[lesson.title] = lessonTasks.map((task, idx) => {
          // For 1-task-per-lesson, globalIndex is just lessonIndex
          // or we can find it in the main tasks list
          const globalIndex = tasks.findIndex(t => t.id === task.id);
          return {
            ...task,
            globalIndex: globalIndex,
            // Use the actual ID (1-1) instead of legacy t1 format
            taskId: task.id,
            lessonIndex: lessonIndex
          };
        });
      });

      setLessonTaskMap(mapping);
    }
  }, [lessons, tasks]);

  const goToTask = (taskId, globalIndex) => {
    setCurrentNode(globalIndex);
    router.push(`/task/${taskId}?track=${name}`);
  };

  const toggleLesson = (lessonTitle) => {
    setActiveLesson(activeLesson === lessonTitle ? null : lessonTitle);
  };

  const calculateProgress = () => {
    // Only count completed tasks that are actually in our current curriculum
    if (!tasks.length) return 0;
    const validCompletedCount = tasks.filter(t => completedTaskIds.has(t.id)).length;
    return Math.min(100, (validCompletedCount / tasks.length) * 100);
  };

  const getLessonProgress = (lessonTitle) => {
    const lessonTasks = lessonTaskMap[lessonTitle] || [];
    if (lessonTasks.length === 0) return 0;

    const completed = lessonTasks.filter(task => completedTaskIds.has(task.taskId)).length;
    return (completed / lessonTasks.length) * 100;
  };

  return (
    <main className={styles.wrapper}>
      <div className={styles.layout}>
        <Sidebar />

        <section className={styles.content}>

          <div className={styles.header}>
            <h1 className={styles.title}>{decodeURIComponent(name).replaceAll("-", " ")
            }</h1>
            <p className={styles.subtitle}>Your interactive learning journey</p>

            <div className={styles.controls}>
              <button
                className={`${styles.filterBtn} ${showCompleted ? styles.active : ''}`}
                onClick={() => setShowCompleted(!showCompleted)}
              >
                {showCompleted ? 'Hide Completed' : 'Show Completed'}
              </button>
              <div className={styles.stats}>
                <span className={styles.statItem}>
                  <span className={styles.statNumber}>{lessons.length}</span> Lessons
                </span>
                <span className={styles.statItem}>
                  <span className={styles.statNumber}>{tasks.length}</span> Tasks
                </span>
                <span className={styles.statItem}>
                  <span className={styles.statNumber}>{Math.round(calculateProgress())}%</span> Complete
                </span>
              </div>
            </div>
          </div>

          <div className={styles.journeyContainer}>
            {/* TIMELINE NAVIGATION */}
            <div className={styles.timelineNav}>
              {lessons.map((lesson, idx) => {
                const progress = getLessonProgress(lesson.title);
                return (
                  <div
                    key={lesson.title}
                    className={styles.navItem}
                    onClick={() => {
                      const lessonTasks = lessonTaskMap[lesson.title] || [];
                      if (lessonTasks.length > 0) {
                        setCurrentNode(lessonTasks[0].globalIndex);
                      }
                    }}
                  >
                    <div className={styles.navDot}>
                      <div
                        className={styles.navProgress}
                        style={{ height: `${progress}%` }}
                      />
                      <span className={styles.navNumber}>{idx + 1}</span>
                    </div>
                    <span className={styles.navLabel}>{lesson.title}</span>
                  </div>
                );
              })}
            </div>

            {/* MAIN TIMELINE */}
            <div className={styles.timelineWrapper}>
              {/* PATH LINE WITH ANIMATED ELEMENTS */}
              <div className={styles.pathContainer}>
                <div className={styles.pathLine}></div>
                <div className={styles.pathGlow}></div>

                {/* ANIMATED PARTICLES */}
                {/* <div className={styles.particles}>
                  {Array.from({ length: 20 }).map((_, i) => (
                    <div 
                      key={i}
                      className={styles.particle}
                      style={{
                        left: `${Math.random() * 100}%`,
                        animationDelay: `${Math.random() * 2}s`,
                        animationDuration: `${2 + Math.random() * 3}s`
                      }}
                    />
                  ))}
                </div> */}
              </div>

              {/* ROCKET CONTAINER */}
              <div className={styles.rocketContainer}>
                <div
                  className={styles.rocket}
                  style={{
                    transform: `translateY(${currentNode * 120}px)`,
                  }}
                >
                  <div className={styles.rocketBody}>
                    <div className={styles.rocketWindow}></div>
                    <div className={styles.rocketFins}>
                      <div className={styles.rocketFin}></div>
                      <div className={styles.rocketFin}></div>
                    </div>
                    <div className={styles.rocketFlame}></div>
                  </div>
                </div>
              </div>

              {/* LESSONS AND TASKS */}
              <div className={styles.lessonsColumn}>
                {lessons.map((lesson, lessonIdx) => {
                  const lessonTasks = lessonTaskMap[lesson.title] || [];
                  const isExpanded = activeLesson === lesson.title || activeLesson === null;
                  const lessonProgress = getLessonProgress(lesson.title);

                  return (
                    <div
                      key={lesson.title}
                      className={`${styles.lessonCard} ${isExpanded ? styles.expanded : ''}`}
                      onClick={() => toggleLesson(lesson.title)}
                    >
                      {/* LESSON HEADER */}
                      <div className={styles.lessonHeader}>
                        <div className={styles.lessonIcon}>
                          <span className={styles.iconNumber}>{lessonIdx + 1}</span>
                          <div
                            className={styles.progressRing}
                            style={{
                              background: `conic-gradient(#00d4ff ${lessonProgress}%, rgba(124, 58, 237, 0.2) ${lessonProgress}% 100%)`
                            }}
                          />
                        </div>

                        <div className={styles.lessonInfo}>
                          <div className={styles.lessonTitleRow}>
                            <h2 className={styles.lessonTitle}>{lesson.title}</h2>
                            <span className={styles.taskCount}>
                              {lessonTasks.length} tasks
                            </span>
                          </div>
                          <p className={styles.lessonDesc}>{lesson.description}</p>
                          <div className={styles.progressBar}>
                            <div
                              className={styles.progressFill}
                              style={{ width: `${lessonProgress}%` }}
                            />
                          </div>
                        </div>

                        <button className={styles.expandBtn}>
                          {isExpanded ? '▼' : '►'}
                        </button>
                      </div>

                      {/* TASKS GRID */}
                      {isExpanded && (
                        <div className={styles.tasksGrid}>
                          {isLoading ? (
                            <p>Loading tasks...</p>
                          ) : lessonTasks.map((task, taskIdx) => {
                            const isCompleted = completedTaskIds.has(task.taskId);
                            const isCurrent = task.globalIndex === currentNode;

                            if (!showCompleted && isCompleted) return null;

                            return (
                              <div
                                key={task.taskId}
                                className={`${styles.taskCard} ${isCompleted ? styles.completed : ''
                                  } ${isCurrent ? styles.current : ''}`}
                                onClick={(e) => {
                                  e.stopPropagation();
                                  goToTask(task.taskId, task.globalIndex);
                                }}
                              >
                                <div className={styles.taskHeader}>
                                  <div className={styles.taskIcon}>
                                    {isCompleted ? (
                                      <div className={styles.completedIcon}>✓</div>
                                    ) : (
                                      <div className={styles.taskNumber}>{task.globalIndex + 1}</div>
                                    )}
                                  </div>

                                  <div className={styles.taskStatus}>
                                    <span className={styles.statusBadge}>
                                      {isCurrent ? 'Current' : isCompleted ? 'Completed' : 'Upcoming'}
                                    </span>
                                  </div>
                                </div>

                                <div className={styles.taskContent}>
                                  <h3 className={styles.taskLabel}>{task.label}</h3>
                                  <p className={styles.taskDesc}>
                                    {task.description || 'Complete this task to advance'}
                                  </p>
                                </div>

                                <div className={styles.taskFooter}>
                                  <div className={styles.difficulty}>
                                    <span className={styles.diffLabel}>
                                      Difficulty: {task.difficulty || 'Medium'}
                                    </span>
                                  </div>
                                  <button className={styles.startBtn}>
                                    {isCurrent ? 'Continue →' : isCompleted ? 'Review' : 'Start'}
                                  </button>
                                </div>

                                {/* HOVER EFFECTS */}
                                <div className={styles.taskHoverEffect}></div>
                                {isCurrent && <div className={styles.currentPulse}></div>}
                              </div>
                            );
                          })}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          </div>

          {/* PROGRESS OVERVIEW */}
          <div className={styles.progressOverview}>
            <div className={styles.progressHeader}>
              <h3>Journey Progress</h3>
              <span>{Math.round(calculateProgress())}% Complete</span>
            </div>

            <div className={styles.progressDetails}>
              <div className={styles.progressMeter}>
                <div
                  className={styles.meterFill}
                  style={{ width: `${calculateProgress()}%` }}
                />
                <div className={styles.meterLabels}>
                  {Array.from({ length: Math.min(tasks.length, 6) }).map((_, i) => {
                    const idx = Math.floor((tasks.length - 1) * (i / 5));
                    return (
                      <span
                        key={i}
                        className={`${styles.meterLabel} ${idx <= currentNode ? styles.active : ''}`}
                      >
                        Task {idx + 1}
                      </span>
                    );
                  })}
                </div>
              </div>

              <div className={styles.statsGrid}>
                <div className={styles.statCard}>
                  <div className={styles.statIcon}>📚</div>
                  <div className={styles.statContent}>
                    <span className={styles.statValue}>{lessons.length}</span>
                    <span className={styles.statLabel}>Lessons</span>
                  </div>
                </div>

                <div className={styles.statCard}>
                  <div className={styles.statIcon}>✅</div>
                  <div className={styles.statContent}>
                    <span className={styles.statValue}>
                      {currentNode + 1} / {tasks.length}
                    </span>
                    <span className={styles.statLabel}>Tasks Completed</span>
                  </div>
                </div>

                <div className={styles.statCard}>
                  <div className={styles.statIcon}>⏱️</div>
                  <div className={styles.statContent}>
                    <span className={styles.statValue}>
                      {Math.round((tasks.length - currentNode - 1) * 15)}
                    </span>
                    <span className={styles.statLabel}>Est. Time Remaining (min)</span>
                  </div>
                </div>

                <div className={styles.statCard}>
                  <div className={styles.statIcon}>🚀</div>
                  <div className={styles.statContent}>
                    <span className={styles.statValue}>
                      {Math.round(calculateProgress())}%
                    </span>
                    <span className={styles.statLabel}>Overall Progress</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <Footer />
        </section>
      </div>
    </main>
  );
}